name: Build Android APK

on:
  push:
    branches:
      - main  # Or your main branch name
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Use a specific, supported Python version

    - name: Install system dependencies (important for some Kivy recipes)
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential libssl-dev libffi-dev python3-dev

    - name: Install Buildozer
      run: pip install buildozer

    - name: Cache Buildozer downloads
      uses: actions/cache@v4
      with:
        path: ./build_downloads  # Cache the download_dir we specified
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: digifriend-apk
        path: bin/*.apk
        if-no-files-found: error
